#pragma once

#define MATRIX_ROWS 5
#define MATRIX_COLS 5
#define MATRIX_ROW_PINS { GP2, GP3, GP4, GP5, GP6 }
#define MATRIX_COL_PINS { GP7, GP8, GP9, GP10, GP11 }

#define SERIAL_USART_TX_PIN GP0
#define SERIAL_USART_RX_PIN GP1
#define SERIAL_USART_DRIVER SIOD0
#define SPLIT_HAND_PIN GP15

#define MATRIX_ROW_PINS_RIGHT { GP6, GP7, GP8, GP9 }
#define MATRIX_COL_PINS_RIGHT { GP10, GP11, GP12, GP13, GP14 }

#define ENCODER_RESOLUTION 1

#define ENCODERS_PAD_A { GP21, GP26, GP12 }
#define ENCODERS_PAD_B { GP22, GP27, GP13 }

#define ENCODERS_PAD_A_RIGHT { GP21 }
#define ENCODERS_PAD_B_RIGHT { GP22 }

